### ISSUE TITLE
Convert pub_date to datetime field

### ISSUE THREAD

**Issue by smoeinbbp** [codehub-ir/codehub#20]
Hi @lnxpy ,
Isn't it better to store pub_date as a datetime field and write an utility function to communicate with the **calendar** method in order to convert datetimes?

**Comment by lnxpy** [comment]
Hi dear Moein khan,

Hope you are doing well. It's been a long time since these model fields were left dirty. That's awkward to keep converting dates over and over otherwise, in the [new version](https://github.com/lnxpy/codehub/blob/28351c92f1af621a5397a21f3f4d935e6949b3b6/main/models.py#L37), I've used [django_jalali](https://github.com/slashmili/django-jalali) in order to keep them in Shamsi.

Thank you so much for your incredible support :heart:

**Comment by smoeinbbp** [comment]
> Hi dear Moein khan,
> 
> Hope you are doing well. It's been a long time since these model fields were left dirty. That's awkward to keep converting dates over and over otherwise, in the [new version](https://github.com/lnxpy/codehub/blob/28351c92f1af621a5397a21f3f4d935e6949b3b6/main/models.py#L37), I've used [django_jalali](https://github.com/slashmili/django-jalali) in order to keep them in Shamsi.
> 
> Thank you so much for your incredible support :heart:

So this repo is not updated, right? When can I (and also other developers) contribute to this repo?

**Comment by lnxpy** [comment]
That's it. I keep developing on [lnxpy/codehub](https://github.com/lnxpy/codehub) and CodeHub is up to date there. Once the project is stabilized, all PRs and issues will be tracked. I will mention you in the future posts on LinkedIn about the stable version and release time if you don't mind actually.

**Comment by smoeinbbp** [comment]
Yes, of course. I'll be happy to contribute.

**Comment by lnxpy** [comment]
That's honorable to me to have you as a contributor. ❤️ 
Thank you so much.
