### ISSUE TITLE
Download buttons have no font

### ISSUE THREAD

**Issue by sina-yeganeh** [codehub-ir/codehub#39]
Hello! 
First I should say your project is awesome!
this buttons have no font :)
![Screenshot_select-area_20211227222656](https://user-images.githubusercontent.com/71815150/147499890-6d78a475-6a62-4a1e-a79a-1c5c9c9911eb.jpg)

**Comment by lnxpy** [comment]
Hi Sina,

Thanks for checking out. I latterly appreciate it. This issue happens when you put a text within AwesomeIcon-styled tags like `<span class="fa ..">` or `<i class="fa ..">`. All things needed is to either override the `font-family` for each `span` or `i` or, put the text outside of the styled tag which is actually more preferred.

Do you want to give it a go and fix this bug though? (Just make a new PR and link the issue and tell more about the issue and fixes)

Best wishes,
Alireza
